### ISSUE TITLE
Add JSON output format

### ISSUE THREAD

**Issue by jpraet** [belgif/rest-guide-validator#26]
Add a new JSON output option, with all violations in a single structured output file.

original request:
----
At CBSS we have some tooling that parses the JUnit report generated by the rest-guide-validator.

(when validating openapi of external suppliers, we only want to fail on a certain subset of rules we consider as critical, and also ignore violations on paths / operations that are not used by CBSS)

The structure of this JUnit report changed in 2.0, and seems more difficult to parse as there is no longer an entry for each violation.
Everything is now grouped under a single testcase per file (or per rule, depending on groupBy configuration).

[TEST-swagger.yaml-old.xml.txt](https://github.com/user-attachments/files/17013296/TEST-swagger.yaml-old.xml.txt)
[TEST-swagger.yaml-new.xml.txt](https://github.com/user-attachments/files/17013300/TEST-swagger.yaml-new.xml.txt)

Could the structure of the generated JUnit report be revisited?
Or maybe an additional structured output format could be supported (XML / JSON) that is more suitable for parsing by other tools?

**Comment by jpraet** [comment]
We don't use the JUnit XML report in Jenkins, so a new JSON output format is OK for me.

**Comment by pvdbosch** [comment]
2.1.0 has been released with this feature
