### ISSUE TITLE
Shouldn't fail if the YAML or JSON is not available

### ISSUE THREAD

**Issue by GodwinMaravai** [belgif/rest-guide-validator#32]
Hi,

I expect the Maven plugin shouldn't fail if the YAML or JSON is not available in the specified folder, i.e.:  `rest-guide-validator.files`.

In a situation, where I have a parent pom.xml (packaging as `pom`) and all my REST applications/projects are using the parent pom as a parent then it will be easy to define the plugin in the parent pom.xml instead of repeating the same plugin in the each REST applications/projects pom.xml.

Parent pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>be</groupId>
    <artifactId>parent-common</artifactId>
    <version>0.1.0</version>
    <packaging>pom</packaging>

    <name>parent-common</name>
    <description>Common functionality that is shared between all REST projects.</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.1</version>
        <relativePath/>
    </parent>

    <build>
        <plugins>
            <plugin>
                ....
            </plugin>
            <!-- The plugin to validate if an OpenAPI document conforms to the guidelines in the Belgif REST guide (https://www.belgif.be/specification/rest/api-guide/) -->
            <plugin>
                <groupId>io.github.belgif.rest.guide.validator</groupId>
                <artifactId>belgif-rest-guide-validator-maven-plugin</artifactId>
                <version>2.1.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <files>
                        <folder>.swagger-codegen/</folder>
                    </files>
                    <outputTypes>CONSOLE</outputTypes>
                    <groupBy>file</groupBy>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

Then in all my REST applications that use the `be:parent-common:0.1.0` as a parent, I don't need to add the same plugin in all my REST applications.

But as of now since the `be:parent-common:0.1.0` doesn't have the OpenApi YAML or JSON files in `.swagger-codegen/` location, it fails during the Maven build.

**Comment by pvdbosch** [comment]
Desired behavior may depend on how it's used: if plug-in is configured to point to a specific OpenAPI file, it can be desirable to have it fail because there's an error in the config then e.g. after the file is renamed.

We could introduce a <failOnMissingOpenAPI> config parameter which defaults to `false` (i.e. current behavior).
