### ISSUE TITLE
Upgrade to JDK 17

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide-validator#9]
Analyze if we can update to JDK 17. This requires JDK >= 17 when running Maven (usually determined by JDK_HOME env var), but compilation of project code using the plugin can still be done by an earlier JDK version in the pom configuration.

@jpraet : is CBSS okay with updating the JDK requirement for the plugin?
Still to check for other large users.

Implementation of update already in  https://github.com/belgif/rest-guide-validator/pull/8

**Comment by jpraet** [comment]
Yes, CBSS uses JDK 21 to run Maven on workstations and jenkins.
